// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UtilityPaymentManager.Models;

#nullable disable

namespace UtilityPaymentManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230516153931_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("UtilityPaymentManager.Models.Counter", b =>
                {
                    b.Property<int>("CounterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CounterId"), 1L, 1);

                    b.Property<decimal>("CurrentNumber")
                        .HasColumnType("decimal(5,3)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("CounterId");

                    b.ToTable("Counters");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Counter");
                });

            modelBuilder.Entity("UtilityPaymentManager.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"), 1L, 1);

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Sum")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("PaymentId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("UtilityPaymentManager.Models.PaidCounter", b =>
                {
                    b.HasBaseType("UtilityPaymentManager.Models.Counter");

                    b.Property<decimal>("ChangeAmount")
                        .HasColumnType("decimal(5,3)");

                    b.Property<int>("PaidCounterId")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int");

                    b.HasIndex("PaymentId");

                    b.HasDiscriminator().HasValue("PaidCounter");
                });

            modelBuilder.Entity("UtilityPaymentManager.Models.PaidCounter", b =>
                {
                    b.HasOne("UtilityPaymentManager.Models.Payment", null)
                        .WithMany("PaidCounters")
                        .HasForeignKey("PaymentId");
                });

            modelBuilder.Entity("UtilityPaymentManager.Models.Payment", b =>
                {
                    b.Navigation("PaidCounters");
                });
#pragma warning restore 612, 618
        }
    }
}
